<a href="https://colab.research.google.com/github/PatrickCortes/Linear--Algbebra_ChE_2nd-Sem-2021-2022/blob/main/Matrix_(description_Operations).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.



In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline


## Matrices

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
   w-2x+3y-4z \\
   3w-x-2y+z \\
   2w-x+3y-2z
    \end{array}
\right. \\
$$

### Given the matrix below, express it as a linear combination in a markdown.


$$
G = \left\{
    \begin{array}\
       x_1+7x_2+8x_3\\
        2x_2+2x_3+2x_4\\ 
        4x_3+6x_2+7x_4
    \end{array}
\right. 
$$

$$
G = \begin{bmatrix} 1 & 7 &8 \\ 2 & 2 & 2\\ 4 & 6 & 7\end{bmatrix} \\
$$

### Given the matrix below, display the output as a LaTeX makdown also express it as a system of linear combinations.

$$
H = \begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0\\ 4 & 6 & 7\end{bmatrix} \\
$$

$$
H = \left\{
    \begin{array}\
       x_1\\
        2x_2+2x_3\\ 
        4x_3+6x_2+7x_4
    \end{array}
\right. 
$$

##matrix 

$$
A=\begin{bmatrix} 4 & 4 \\ 4 & -10\end{bmatrix} \\
B=\begin{bmatrix} 1 & 8 & 1 \\ 3 & -7 & -4 \\ -2 & 4 & 2\end{bmatrix}\\
C =\begin{bmatrix} 5 & -1 & 3 & 8 \\ 3 & 10 & -2 & 1 \\ -6 &-1 & -1 & 8\end{bmatrix}\\ $$

$$
\theta=\begin{bmatrix} \ 5x+3y-z\end{bmatrix} 
$$




## Declaring Matrices

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [ ]:
## Since we'll be  discussing matrix. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')


In [ ]:
## declaring a 3 x 3 matrix
A = np.array([
    [1, -5, -2],
    [5, 2, -8],
    [4, -6, -10]
])
describe_mat(A)



Matrix:
[[  1  -5  -2]
 [  5   2  -8]
 [  4  -6 -10]]

Shape:	(3, 3)
Rank:	2



In [ ]:
## declaring 2 x 3 matrix
G = np.array([
    [-1,5,7],
    [4,3,9]
])
describe_mat(G)


Matrix:
[[-1  5  7]
 [ 4  3  9]]

Shape:	(2, 3)
Rank:	2



In [ ]:
## declaring a 3 x 2 matrix 
B = np.array([
    [300, 40],
    [10, 80],
    [1400, 112023]
])
describe_mat(B)


Matrix:
[[   300     40]
 [    10     80]
 [  1400 112023]]

Shape:	(3, 2)
Rank:	2



In [ ]:
H = np.array([
              1,2,3,4
              ])
describe_mat(H)


Matrix:
[1 2 3 4]

Shape:	(4,)
Rank:	1



## Categorizing Matrices

There are several ways of  classifying matrices. One could be according to its shape and another is according to their element values. We'll try to go through them. 

## According to shape 

### Row and Column Matrices


In [ ]:
## Declaring a Row Matrix

rowmatrix1D = np.array([
    3, -6, 2, -10
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [50,28,32, -41]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)


Matrix:
[  3  -6   2 -10]

Shape:	(4,)
Rank:	1

Matrix:
[[ 50  28  32 -41]]

Shape:	(1, 4)
Rank:	2



In [ ]:
## declaring a column matrix
col_mat = np.array([
    [1],
    [2],
    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)


Matrix:
[[1]
 [2]
 [5]]

Shape:	(3, 1)
Rank:	2



# Square Matrix

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')


In [ ]:
square_mat = np.array([
    [1,3,7],
    [3,4,6],
    [-13,5,6]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)


Matrix:
[[  1   3   7]
 [  3   4   6]
 [-13   5   6]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2
Is Square: False



## Null Matrix

In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs square: {is_square}\n')
    else:
        print('Matrix is Null')


In [ ]:
null_mat = np.array([])
describe_mat(null_mat)


Matrix is Null


### Zero Matrix 

In [ ]:

zero_mat_row = np.zeros((4,7))
zero_mat_sqr = np.zeros((5,4))
zero_mat_rct = np.zeros((6,7))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

describe_mat(zero_mat_row)
describe_mat(zero_mat_sqr)
describe_mat(zero_mat_rct)



Zero Row Matrix: 
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
Zero Square Matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
Matrix:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

Shape:	(4, 7)
Rank:	2
Is square: False

Matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Shape:	(5, 4)
Rank:	2
Is square: False

Matrix:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

Shape:	(6, 7)
Rank:	2
Is square: False



### Ones Matrix

In [ ]:

      
ones_mat_row = np.ones((5,2))
ones_mat_sqr = np.ones((4,6))
ones_mat_rct = np.ones((5,7))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')


Ones Row Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Ones Square Matrix: 
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


Diagonal Matrix

In [ ]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])
#a[1,1], a[2,2], a[3,3]...a[n-1,n-1]


array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [ ]:
d = np.diag([6,4,2,8])
#d.shape[0] == d.shape[1]
d

array([[6, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 8]])

### Identity matrix 

In [ ]:
np.eye(15)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [ ]:
np.identity(10)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Upper Triangular Matrix

In [ ]:
np.array([
    [1,2,3,4],
    [0,3,1,-1],
    [0,0,5,2],
    [0,0,0,2]
])


array([[ 1,  2,  3,  4],
       [ 0,  3,  1, -1],
       [ 0,  0,  5,  2],
       [ 0,  0,  0,  2]])

In [ ]:
F = np.array([
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],


In [ ]:
F = np.array([
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
])
np.triu(F)


array([[ 2, -3,  4, -5,  6],
       [ 0, -3,  4, -5,  6],
       [ 0,  0,  4, -5,  6],
       [ 0,  0,  0, -5,  6],
       [ 0,  0,  0,  0,  6]])

In [ ]:
F = np.array([
              [4, -6, -1, 7, -8],
              [4, -6, -1, 7, -8],
              [4, -6, -1, 7, -8],
              [4, -6, -1, 7, -8],
              [4, -6, -1, 7, -8],
])
np.triu(F)

array([[ 4, -6, -1,  7, -8],
       [ 0, -6, -1,  7, -8],
       [ 0,  0, -1,  7, -8],
       [ 0,  0,  0,  7, -8],
       [ 0,  0,  0,  0, -8]])

### Lower Triangular Matrix

In [ ]:
np.tril(F)


array([[ 4,  0,  0,  0,  0],
       [ 4, -6,  0,  0,  0],
       [ 4, -6, -1,  0,  0],
       [ 4, -6, -1,  7,  0],
       [ 4, -6, -1,  7, -8]])

Given the linear combination below, try to create a corresponding matrix representing it.


:$$\theta = 5x + 3y - z$$


2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [ ]:
H = np.tril(G)
H


array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

## Matrix Algebra

In [9]:
A = np.array([
             [1,2],
              [23,2],
              [6,2],
])

In [10]:
B = np.array([
    [2,2],
    [0,0],
    [1,1]
])
A+B

array([[ 3,  4],
       [23,  2],
       [ 7,  3]])

In [11]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[ 3,  4],
       [25,  4],
       [ 8,  4]])

## Subtraction

In [12]:
A-B

array([[-1,  0],
       [23,  2],
       [ 5,  1]])

In [13]:
A@B

ValueError: ignored

In [14]:
alpha=10**-10
A/(alpha+B)

array([[5.0e-01, 1.0e+00],
       [2.3e+11, 2.0e+10],
       [6.0e+00, 2.0e+00]])

In [15]:
np.add(A,B)

array([[ 3,  4],
       [23,  2],
       [ 7,  3]])



$$

B=\begin{matrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{matrix}

$$



$$

B = \left\{
    \begin{array}\

        x+y+z \\ 

        3x -2y -z \\

        -x + 4y +2z

    \end{array}

\right. $$

In [ ]:
i = 0
while i < 5:
  print(i)
  i += 1
  if i == 3:
    break
  else:
    print(0)



0
0
1
0
2


In [ ]:
import numpy as np
X = np.array([
         [5,0,4],
        [4,-1,5],
        [3,-1,-6]
])
Y = np.triu(X)
Y

array([[ 5,  0,  4],
       [ 0, -1,  5],
       [ 0,  0, -6]])

In [ ]:
d = {0,1,2}
for x in d:
  print(x)

0
1
2


In [ ]:
def create_user (userid):
    print("Successfully created user: {}".format(userid))

userid = 2021_100001
create_user(2021-100100)
 


Successfully created user: -98079


In [ ]:
x = 1
while True:
  if x % 5 == 0:
    break
    print(x)
    x + = 1

SyntaxError: ignored

In [ ]:
P = np.array([
              [5,7,2],
              [2,3,3],
              [4,1,0]

])
Q = np.array([
              [2,2,-3],
              [0,0,1],
              [1,1,-3]
])
P + 2*Q

array([[ 9, 11, -4],
       [ 2,  3,  5],
       [ 6,  3, -6]])

## sample matrices

In [ ]:
G = np.array([
    [-1,5,7, -3],
    [4,3,9, 5],
    [5,-8,-2,1],
    [11,13,14,15]
])
describe_mat(G)

Matrix:
[[-1  5  7 -3]
 [ 4  3  9  5]
 [ 5 -8 -2  1]
 [11 13 14 15]]

Shape:	(4, 4)
Rank:	2
Is square: True



In [ ]:
j = np.array([
    [-13,15,72, -34,61],
    [13,35,23, 35,12],
    [51,-82,-23,16,24],
    
])
describe_mat(j)

Matrix:
[[-13  15  72 -34  61]
 [ 13  35  23  35  12]
 [ 51 -82 -23  16  24]]

Shape:	(3, 5)
Rank:	2
Is square: False



In [ ]:
F = np.array([
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
])
describe_mat(F)
np.triu(F)


Matrix:
[[ 2 -3  4 -5  6]
 [ 2 -3  4 -5  6]
 [ 2 -3  4 -5  6]
 [ 2 -3  4 -5  6]
 [ 2 -3  4 -5  6]]

Shape:	(5, 5)
Rank:	2
Is square: True



array([[ 2, -3,  4, -5,  6],
       [ 0, -3,  4, -5,  6],
       [ 0,  0,  4, -5,  6],
       [ 0,  0,  0, -5,  6],
       [ 0,  0,  0,  0,  6]])

In [ ]:
d = np.diag([6,4,2,8])
#d.shape[0] == d.shape[1]
describe_mat(d)
d

Matrix:
[[6 0 0 0]
 [0 4 0 0]
 [0 0 2 0]
 [0 0 0 8]]

Shape:	(4, 4)
Rank:	2
Is square: True



array([[6, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 8]])

## Task 1 
Create a function named mat_desc() that througouhly describes a matrix, it should:

Displays the shape, size, and rank of the matrix.
Displays whether the matrix is square or non-square.
Displays whether the matrix is an empty matrix.
Displays if the matrix is an identity, ones, or zeros matrix
Use 5 sample matrices in which their shapes are not lower than . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [2]:
## Function Area
import numpy as np


In [1]:
## Matrix Declarations

def mat_desc(mat):
    sq = False
    mat = np.array(mat)
    print(mat)
    print('Shape:', mat.shape)
    print('Size:', mat.size)
    print('Rank:', np.linalg.matrix_rank(mat))
    if(mat.shape[0] == mat.shape[1]):
        sq = True
        print('The matrix is square')
    else:
        print('The matrix is non-square')
    if(mat.shape[0] == 0 and mat.shape[1] == 0):
        print('The matrix is empty')
    else:
        print('The matrix is not empty')
    iden = np.identity(mat.shape[0])
    if(sq and (iden == mat).all()):
        print('The matrix is an identity matrix')
    else:
        print('The matrix is not an identity matrix')
    one = np.ones((mat.shape[0], mat.shape[1]))
    if((one == mat).all()):
        print('The matrix is a ones matrix')
    else:
        print('The matrix is not an ones matrix')
    zero = np.zeros((mat.shape[0], mat.shape[1]))
    if((zero == mat).all()):
        print('The matrix is a zeros matrix')
    else:
        print('The matrix is not a zeros matrix')

In [3]:
## Sample Matrices
print('Matrix 1:')
mat_desc([[0,0,0,0], [0, 0, 0,0], [0,0,0,0]])
print('Matrix 2:')
mat_desc([[4, 3, 0, 1], [2, 6, 2,5], [7, 1, 2, 8]])
print('Matrix 3:')
mat_desc([[1, 3, 2, 2], [4, 7, 6, 2], [5, 6, 9, 4]])
print('Matrix 4:')
mat_desc([[1,1,1],[1,1,1],[1,1,1],[1,1,1], [1,1,1]])
print('Matrix 5:')
mat_desc([[7,1,5,0],[1,6,2,0],[4,8,6,9],[7,2,1,0],[1,9,1,5]])

Matrix 1:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Shape: (3, 4)
Size: 12
Rank: 0
The matrix is non-square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is a zeros matrix
Matrix 2:
[[4 3 0 1]
 [2 6 2 5]
 [7 1 2 8]]
Shape: (3, 4)
Size: 12
Rank: 3
The matrix is non-square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix
Matrix 3:
[[1 3 2 2]
 [4 7 6 2]
 [5 6 9 4]]
Shape: (3, 4)
Size: 12
Rank: 3
The matrix is non-square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix
Matrix 4:
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
Shape: (5, 3)
Size: 15
Rank: 1
The matrix is non-square
The matrix is not empty
The matrix is not an identity matrix
The matrix is a ones matrix
The matrix is not a zeros matrix
Matrix 5:
[[7 1 5 0]
 [1 6 2 0]
 [4 8 6 9]
 [7 2 1 0]
 [1 9 1 5]]
Shape: (5, 4)
Size: 20


## Task 2
Create a function named mat_operations() that takes in two matrices a input parameters it should:

1. Determines if the matrices are viable for operation and returns your 
 own error message if they are not viable.
2. Returns the sum of the matrices.
3. Returns the different of the matrices.
4. Returns the element-wise multiplication of the matrices.
5. Returns the element-wise division of the matrices.
Use 5 sample matrices in which their shapes are not lower than (3x3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [4]:
## Function Area
import numpy as np

In [5]:
def mat_operations(mat1, mat2):
    mat1 = np.array(mat1)
    mat2 = np.array(mat2)
    print('Matrix 1:', mat1)
    print('Matrix 2:', mat2)
    if(mat1.shape != mat2.shape):
        print('The matrices are not equal and invalid size operation.')
        return
    print('Sum of the  matrices:')
    matsum = mat1 + mat2
    print(matsum)
    print('Difference of the  matrices:')
    matdiff = mat1 - mat2
    print(matdiff)
    print('Element-wise multiplication of the  matrices:')
    matmul = np.multiply(mat1, mat2)
    print(matmul)
    print('Element-wise division of the  matrices:')
    matdiv = np.divide(mat1, mat2)
    print(matdiv)

In [6]:
print('sample1:')
mat_operations([[2,3,2], [5,4,7], [4,3,8]],[[3,4,5], [9,7,1],[1,2,6]])

print('sample 2:')
mat_operations([[2, 6, 3,4], [3,3,1,5], [5,1,5,7]], [[3,7,5,7],[1,2,1,9],[1,1,1,6]])

print('sample 3:')
mat_operations([[2, 5, 1], [3,6,3], [6,1,5]], [[5,4,2],[3,4,6],[3,2,3]])

print('sample 4:')
mat_operations([[6,2,1,8,2], [3,6,3,7,8], [6,1,5,9,2]], [[5,4,2,7,7],[3,4,6,8,9],[3,2,3,6,2]])

print('sample 5:')
mat_operations([[6,2,1,8,2,5], [3,6,3,7,8,8], [6,1,5,9,2,2]], [[5,4,2,7,7,8],[3,4,6,8,9,2],[3,2,3,6,2,1]])


sample1:
Matrix 1: [[2 3 2]
 [5 4 7]
 [4 3 8]]
Matrix 2: [[3 4 5]
 [9 7 1]
 [1 2 6]]
Sum of the  matrices:
[[ 5  7  7]
 [14 11  8]
 [ 5  5 14]]
Difference of the  matrices:
[[-1 -1 -3]
 [-4 -3  6]
 [ 3  1  2]]
Element-wise multiplication of the  matrices:
[[ 6 12 10]
 [45 28  7]
 [ 4  6 48]]
Element-wise division of the  matrices:
[[0.66666667 0.75       0.4       ]
 [0.55555556 0.57142857 7.        ]
 [4.         1.5        1.33333333]]
sample 2:
Matrix 1: [[2 6 3 4]
 [3 3 1 5]
 [5 1 5 7]]
Matrix 2: [[3 7 5 7]
 [1 2 1 9]
 [1 1 1 6]]
Sum of the  matrices:
[[ 5 13  8 11]
 [ 4  5  2 14]
 [ 6  2  6 13]]
Difference of the  matrices:
[[-1 -1 -2 -3]
 [ 2  1  0 -4]
 [ 4  0  4  1]]
Element-wise multiplication of the  matrices:
[[ 6 42 15 28]
 [ 3  6  1 45]
 [ 5  1  5 42]]
Element-wise division of the  matrices:
[[0.66666667 0.85714286 0.6        0.57142857]
 [3.         1.5        1.         0.55555556]
 [5.         1.         5.         1.16666667]]
sample 3:
Matrix 1: [[2 5 1]
 [3 6 3]
 [6 1